services:
  - type: web
    name: facebook-monitor1
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python3 main.py
    envVars:
      - key: C_USER
        sync: false
      - key: XS
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    autoDeploy: true